FROM python:3.11-slim AS builder

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  PATH="/root/.local/bin:$PATH" \
  # Poetry's configuration:
  POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_CREATE=false

COPY ./.docker/files/fastapi/install.sh .

RUN sed -i -e 's/\r$//' ./install.sh

RUN ./install.sh

RUN rm ./install.sh

# System deps:
RUN curl -sSL https://install.python-poetry.org | python3 -

WORKDIR /app
# Copy only requirements to cache them in docker layer and prevent reinstalling them if there are no dep changes
COPY poetry.lock pyproject.toml ./

# Project initialization:
RUN poetry install --no-interaction --no-ansi --no-root --only main

FROM python:3.11-slim
ARG UID=1000
ARG GID=1000

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  PATH="/root/.local/bin:$PATH"

COPY ./.docker/files/fastapi/install.sh .

RUN sed -i -e 's/\r$//' ./install.sh

RUN ./install.sh

RUN rm ./install.sh

# create basicuser for container and use the GID/UID from the host build user (if provided)
RUN groupadd -g $GID basicuser && useradd -r -u $UID -g basicuser basicuser

RUN mkdir -p /home/basicuser && chown basicuser:basicuser -R /home/basicuser

USER basicuser

ENV PATH="/home/basicuser/.local/bin:${PATH}"

WORKDIR /app
# Copy the current directory contents into the container at /app
COPY --chown=basicuser:basicuser api ./api/

# Copy dependencies from builder stage
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

RUN python3 -m api.cli refresh-all

EXPOSE 8000

# run the command to start the api
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
